version: '3.8'

services:
  mysql:
    container_name: springboot_al_mysql
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=springboot_al
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
